<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="devopsml" nsURI="http://www.example.org/devopsml" nsPrefix="devopsml">
  <eClassifiers xsi:type="ecore:EClass" name="DevOpsML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelingcapability" upperBound="-1"
        eType="#//ModelingCapability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="#//Language" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" upperBound="-1"
        eType="#//Tool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="public" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="FALSE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelingCapability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelingconcerns" upperBound="-1"
        eType="#//ModelingConcern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languagecharacteristic"
        eType="#//LanguageCharacteristic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tools" upperBound="-1"
        eType="#//Tool" eOpposite="#//Tool/languages"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pragmatics" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" upperBound="-1"
        eType="#//DevOpsPhase" defaultValueLiteral="CODE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="#//Language" eOpposite="#//Language/tools"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devopsprofiles" upperBound="-1"
        eType="#//DevOpsProfile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pragmatics" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdeprofiles" upperBound="-1"
        eType="#//MdeProfile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DevOpsPhase">
    <eLiterals name="CODE"/>
    <eLiterals name="BUILD" value="1"/>
    <eLiterals name="TEST" value="2"/>
    <eLiterals name="RELEASE" value="3"/>
    <eLiterals name="DEPLOY" value="4"/>
    <eLiterals name="OPERATE" value="5"/>
    <eLiterals name="MONITOR" value="6"/>
    <eLiterals name="PLAN" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageCharacteristic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractSyntax" eType="#//AsKind"
        defaultValueLiteral="MOF"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concreteSyntax" eType="#//CsKind"
        defaultValueLiteral="TEXTUAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semantics" eType="#//SemanticsKind"
        defaultValueLiteral="TRANSLATIONAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realization" eType="#//RealizationKind"
        defaultValueLiteral="INTERNAL_DSL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AsKind">
    <eLiterals name="MOF"/>
    <eLiterals name="XML_SCHEMA" value="1" literal="XML_CHEMA"/>
    <eLiterals name="GRAMMAR" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SemanticsKind">
    <eLiterals name="OPERATIONAL"/>
    <eLiterals name="TRANSLATIONAL" value="1" literal="TRANSLATIONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CsKind">
    <eLiterals name="TEXTUAL"/>
    <eLiterals name="GRAPHICAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RealizationKind">
    <eLiterals name="INTERNAL_DSL"/>
    <eLiterals name="EXTERNAL_DSL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RepresentationKind">
    <eLiterals name="GRAPHICAL"/>
    <eLiterals name="TEXTUAL" value="1"/>
    <eLiterals name="IMPOSED_BY_META_LANGUAGE" value="2"/>
    <eLiterals name="MIXED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GenerationKind">
    <eLiterals name="MODEL_TO_TEXT"/>
    <eLiterals name="TEXT_TO_MODEL" value="1"/>
    <eLiterals name="MODEL_TO_MODEL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelingConcern" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pov" lowerBound="1" eType="#//PointOfView"
        defaultValueLiteral="PROCESS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorConcern" eSuperTypes="#//ModelingConcern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//BcKind"
        defaultValueLiteral="FUNCTIONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralConcern" eSuperTypes="#//ModelingConcern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ScKind"
        defaultValueLiteral="SOFTWARE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PointOfView">
    <eLiterals name="PROCESS"/>
    <eLiterals name="PRODUCT" value="1"/>
    <eLiterals name="RESOURCE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BcKind">
    <eLiterals name="FUNCTIONAL"/>
    <eLiterals name="NON_FUNCTIONAL" value="1" literal="NON_FUNCTIONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScKind">
    <eLiterals name="SOFTWARE"/>
    <eLiterals name="HARDWARE" value="1"/>
    <eLiterals name="PHYSICAL" value="2"/>
    <eLiterals name="SOCIETAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DevOpsToolCategory">
    <eLiterals name="AIOPS_ANALYTICS" literal="AIOPS_ANALYTICS"/>
    <eLiterals name="ARTIFACT_PACKAGEMANAGEMENT" value="1" literal="ARTIFACT_PACKAGEMANAGEMENT"/>
    <eLiterals name="CLOUD" value="2"/>
    <eLiterals name="COLLABORATION" value="3"/>
    <eLiterals name="CONFIGURATION_AUTOMATION" value="4" literal="CONFIGURATION_AUTOMATION"/>
    <eLiterals name="CONTAINERS" value="5"/>
    <eLiterals name="CONTINUOUS_INTEGRATION" value="6" literal="CONTINUOUS_INTEGRATION"/>
    <eLiterals name="DATABASE_MANAGEMENT" value="7" literal="DATABASE_MANAGEMENT"/>
    <eLiterals name="DEPLOYMENT" value="8"/>
    <eLiterals name="ENTERPRISE_AGILE_PLANNING" value="9" literal="ENTERPRISE_AGILE_PLANNING"/>
    <eLiterals name="ISSUE_TRAKING_ITSM" value="10" literal="ISSUE_TRAKING_ITSM"/>
    <eLiterals name="RELEASE_MANAGEMENT" value="11" literal="RELEASE_MANAGEMENT"/>
    <eLiterals name="SECURITY" value="12"/>
    <eLiterals name="SERVERLESS_PAAS" value="13" literal="SERVERLESS_PAAS"/>
    <eLiterals name="SOURCECONTROL_MANAGEMENT" value="14" literal="SOURCECONTROL_MANAGEMENT"/>
    <eLiterals name="TESTING" value="15"/>
    <eLiterals name="VALUES_STREAM_MANAGEMENT" value="16" literal="VALUES_STREAM_MANAGEMENT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DevOpsProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//DevOpsToolCategory"
        defaultValueLiteral="COLLABORATION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MdeProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modeling" eType="#//RepresentationKind"
        defaultValueLiteral="GRAPHICAL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generation" eType="#//GenerationKind"
        defaultValueLiteral="MODEL_TO_TEXT"/>
  </eClassifiers>
</ecore:EPackage>
